-- ********************************************
-- * SRAM FILE GENERATED BY HiCoVec ASSEMBLER *
-- *  do not make modifications here          *
-- ********************************************

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity sram is
  generic (
    width_g : positive := 32;
    size_g  : positive := 16
  );
	port (
		clk_i  : in  std_ulogic;
		we_i   : in  std_ulogic;
		en_i   : in  std_ulogic;
		addr_i : in  std_ulogic_vector(size_g-1 downto 0);
		di_i   : in  std_ulogic_vector(width_g-1 downto 0);
		do_o   : out std_ulogic_vector(width_g-1 downto 0)
	);
end sram;
architecture rtl of sram is

	type   ram_t is array(2**size_g-1 downto 0) of std_ulogic_vector(width_g-1 downto 0);
	signal ram : ram_t;
	
begin
	process (clk_i)
	begin
		if clk_i'event and clk_i = '1' then
			if en_i = '1' then
				if we_i = '1' then
					ram(to_integer(unsigned(addr_i))) <= di_i;
					do_o <= di_i;
				else
					do_o <= ram(to_integer(unsigned(addr_i)));
				end if;
			end if;
		end if;
	end process;
end;
